name: Check the code quality using linters and formatters

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  Black:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black[jupyter]

      - name: Run checks
        run: black . --diff --check -t py37
